# Generated by Django 3.2.9 on 2021-11-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя ')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия ')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('company', models.CharField(choices=[('epam', 'EPAM'), ('logic', 'Logig'), ('rozetka', 'Rozetka')], max_length=200, verbose_name='Компания ')),
                ('salary', models.IntegerField(verbose_name='Salary')),
            ],
        ),
    ]
