# Generated by Django 3.2.9 on 2021-11-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя ')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия ')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('company', models.CharField(choices=[('epam', 'EPAM'), ('logic', 'Logic'), ('rozetka', 'Rozetka')], max_length=200, verbose_name='Компания ')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
            ],
        ),
        migrations.DeleteModel(
            name='Form_company',
        ),
    ]
